version: "3"

services:
  frontend:
    build: .
    container_name: frontend
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3001:3000"

    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules


    # stdin_open: true
    # tty: true 
    extra_hosts:
      - "host.docker.internal:172.17.0.1"