version: '3'

services:
  frontend:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: frontend
    ports:
      - "3000:3000"
      - "9009:9009"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
       - tcc-network

networks:
  tcc-network:
    driver: bridge
