version: '3'

services:
  frontend:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: frontend
    ports:
      - "3000:3000"
      - "9009:9009"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
       - tcc-network

networks:
  tcc-network:
    driver: bridge





# version: '3.7'

# services:
#   client:
#     container_name: client
#     build: ./
#     volumes:
#       - './:/app'
#       - '/app/node_modules'
#     ports:
#       - '3000:3000'
#     stdin_open: true
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start





















# version: "3"

# services:
#   frontend:
#     build: .
#     container_name: frontend
#     entrypoint: ./.docker/entrypoint.sh
#     ports:
#       - "3001:3000"

#     volumes:
#       - ./src:/app/src
#       - ./public:/app/public
#       - /app/node_modules


#     stdin_open: true
#     tty: true
#     extra_hosts:
#       - "host.docker.internal:172.17.0.1"