version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3001:3080"
    volumes:
      - .:/app/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"