version: ' 3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart:  always
    depends_on:
      - redis


  frontend:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    tty: true
    build: ./server
    ports:
      - '5000:5000'
    # environment:
    #   DATA_URL: 'postgresql://postgres:postgres@db:5432/postgres?schema=public'
    depends_on:
      - db
    restart: always



  # postgres: &postgres
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  #   restart: always
  #   depends_on:
  #     - redis