version: '3'

services:
  backend:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - tcc-network

  db:
    build: .docker/postgres
    container_name: backend-db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - tcc-network

networks:
  tcc-network:
    driver: bridge


volumes:
  data_postgres: {}
























