version: '3'


services:
  db:
    build: ./postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - tcc-network


networks:
  tcc-network:
      driver: bridge


volumes:
  data_postgres: {}      