version: "3"

services:
  app:
    build: .
    entrypoint: wait-for db:3306 40 -- ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    build: ./.docker/mongo
    restart: always
    tty: true
    volumes:
      - ./.docker/data:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
